{
  lib,
  root,
}: let
  inherit (root.attrsets) removeEmptySets;
in
  #   This function processes a source tree structure (typically generated by the read
  #   function) and removes all entries that don't represent regular files.
  #
  #   Examples:
  #       sources = {
  #         utils = {
  #           "helper.nix" = true;   # kept
  #           "temp.log" = false;    # removed
  #         };
  #         "main.nix" = true;       # kept
  #         "readme.md" = true;     # kept
  #       };
  #
  #       keepRegularFilesOnly sources
  #       => {
  #            utils = { "helper.nix" = true; };
  #            "main.nix" = true;
  #            "readme.md" = true
  #          }
  sources:
    removeEmptySets (
      lib.attrsets.filterAttrsRecursive (
        _: value:
          builtins.isAttrs value || (builtins.isBool value && value)
      )
      sources
    )
