---
name: "Quality"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  check-quality:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@v16"
        with:
          diagnostic-endpoint: ""
      - uses: "DeterminateSystems/magic-nix-cache-action@v8"
        with:
          diagnostic-endpoint: ""
      - name: "Print flake metadata"
        run: "nix flake metadata"
      - uses: "DeterminateSystems/flake-checker-action@v9"
        with:
          fail-mode: true
          ignore-missing-flake-lock: false
          nixpkgs-keys: "nixpkgs"
          send-statistics: false
      - name: "Setup shell"
        run: "nix develop --command true"
      - name: "Flake check"
        run: "nix flake check --all-systems --print-build-logs"
